-- Centralized Comfort Care lead table for Website, Tablet, and Upload sources.
-- Run in Supabase SQL editor before using the live dashboard/forms.

create table if not exists public.leads (
  id bigint generated by default as identity primary key,
  name text not null,
  phone text not null,
  email text,
  care_type text default 'Not sure yet',
  notes text default '',
  location text default '',
  source text not null default 'Website',
  status text not null default 'New',
  relationship_to_resident text,
  move_timeline text,
  payment_type text,
  current_situation text,
  preferred_contact_method text,
  best_contact_time text,
  priority_tags text default '',
  tour_scheduled_at timestamptz,
  follow_up_at timestamptz,
  follow_up_note text default '',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

alter table public.leads
  add column if not exists name text,
  add column if not exists phone text,
  add column if not exists email text,
  add column if not exists care_type text default 'Not sure yet',
  add column if not exists notes text default '',
  add column if not exists location text default '',
  add column if not exists source text not null default 'Website',
  add column if not exists status text not null default 'New',
  add column if not exists relationship_to_resident text,
  add column if not exists move_timeline text,
  add column if not exists payment_type text,
  add column if not exists current_situation text,
  add column if not exists preferred_contact_method text,
  add column if not exists best_contact_time text,
  add column if not exists priority_tags text default '',
  add column if not exists tour_scheduled_at timestamptz,
  add column if not exists follow_up_at timestamptz,
  add column if not exists follow_up_note text default '',
  add column if not exists created_at timestamptz not null default now(),
  add column if not exists updated_at timestamptz not null default now();

create index if not exists leads_created_at_idx on public.leads (created_at desc);
create index if not exists leads_phone_created_at_idx on public.leads (phone, created_at desc);
create index if not exists leads_location_idx on public.leads (location);
create index if not exists leads_source_idx on public.leads (source);
create index if not exists leads_status_idx on public.leads (status);
create index if not exists leads_priority_tags_idx on public.leads (priority_tags);
create index if not exists leads_move_timeline_idx on public.leads (move_timeline);
create index if not exists leads_payment_type_idx on public.leads (payment_type);
create index if not exists leads_tour_scheduled_at_idx on public.leads (tour_scheduled_at);
create index if not exists leads_follow_up_at_idx on public.leads (follow_up_at);

create table if not exists public.lead_events (
  id bigint generated by default as identity primary key,
  lead_id bigint not null,
  event_type text not null,
  detail text default '',
  created_at timestamptz not null default now()
);

create index if not exists lead_events_lead_id_idx on public.lead_events (lead_id, created_at desc);

alter table public.leads enable row level security;

drop policy if exists "Public can insert leads" on public.leads;
create policy "Public can insert leads"
  on public.leads for insert
  to anon
  with check (
    name is not null
    and phone is not null
    and source in ('Website', 'Tablet', 'Upload')
  );

drop policy if exists "Service role full access to leads" on public.leads;
create policy "Service role full access to leads"
  on public.leads for all
  to service_role
  using (true)
  with check (true);

alter table public.lead_events enable row level security;

drop policy if exists "Service role full access to lead events" on public.lead_events;
create policy "Service role full access to lead events"
  on public.lead_events for all
  to service_role
  using (true)
  with check (true);

create table if not exists public.facility_checkins (
  id bigint generated by default as identity primary key,
  visitor_name text not null,
  phone text not null,
  email text,
  community text not null,
  visiting_resident text not null,
  visit_purpose text default 'Family visit',
  notes text default '',
  check_in_source text not null default 'Facility Check-In',
  created_at timestamptz not null default now()
);

create index if not exists facility_checkins_created_at_idx on public.facility_checkins (created_at desc);
create index if not exists facility_checkins_community_idx on public.facility_checkins (community);
create index if not exists facility_checkins_phone_idx on public.facility_checkins (phone);

alter table public.facility_checkins enable row level security;

drop policy if exists "Service role full access to facility checkins" on public.facility_checkins;
create policy "Service role full access to facility checkins"
  on public.facility_checkins for all
  to service_role
  using (true)
  with check (true);

-- Residents directory
create table if not exists public.residents (
  id bigserial primary key,
  name text not null,
  community text not null default '',
  room_number text default '',
  care_level text default 'Assisted Living',
  move_in_date date,
  emergency_contact_name text default '',
  emergency_contact_phone text default '',
  notes text default '',
  status text default 'Active',
  created_at timestamptz default now(),
  updated_at timestamptz default now()
);
alter table public.residents enable row level security;
create policy "Service role full access to residents" on public.residents for all to service_role using (true) with check (true);

-- Incident log
create table if not exists public.incidents (
  id bigserial primary key,
  resident_id bigint references public.residents(id) on delete set null,
  resident_name text default '',
  community text default '',
  type text default 'Other',
  description text not null,
  severity text default 'Low',
  staff_name text default '',
  incident_at timestamptz default now(),
  follow_up_required boolean default false,
  follow_up_notes text default '',
  follow_up_completed boolean default false,
  created_at timestamptz default now(),
  updated_at timestamptz default now()
);
alter table public.incidents enable row level security;
create policy "Service role full access to incidents" on public.incidents for all to service_role using (true) with check (true);
